# Generated by Django 5.1.1 on 2024-11-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre_docente', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('nombre_practica', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('estudiantes_hombres', models.IntegerField()),
                ('estudiantes_mujeres', models.IntegerField()),
            ],
        ),
    ]
